// Code generated by entc, DO NOT EDIT.

package latestblock

const (
	// Label holds the string label denoting the latestblock type in the database.
	Label = "latest_block"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldBlockNumber holds the string denoting the block_number field in the database.
	FieldBlockNumber = "block_number"

	// Table holds the table name of the latestblock in the database.
	Table = "latest_blocks"
)

// Columns holds all SQL columns for latestblock fields.
var Columns = []string{
	FieldID,
	FieldBlockNumber,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}
