// Code generated by entc, DO NOT EDIT.

package migrate

import (
	"github.com/facebook/ent/dialect/sql/schema"
	"github.com/facebook/ent/schema/field"
)

var (
	// LatestBlocksColumns holds the columns for the "latest_blocks" table.
	LatestBlocksColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "block_number", Type: field.TypeUint32},
	}
	// LatestBlocksTable holds the schema information for the "latest_blocks" table.
	LatestBlocksTable = &schema.Table{
		Name:        "latest_blocks",
		Columns:     LatestBlocksColumns,
		PrimaryKey:  []*schema.Column{LatestBlocksColumns[0]},
		ForeignKeys: []*schema.ForeignKey{},
		Indexes: []*schema.Index{
			{
				Name:    "latestblock_block_number",
				Unique:  false,
				Columns: []*schema.Column{LatestBlocksColumns[1]},
			},
		},
	}
	// PostsColumns holds the columns for the "posts" table.
	PostsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID, Unique: true},
		{Name: "title", Type: field.TypeString},
		{Name: "created_at", Type: field.TypeTime},
	}
	// PostsTable holds the schema information for the "posts" table.
	PostsTable = &schema.Table{
		Name:        "posts",
		Columns:     PostsColumns,
		PrimaryKey:  []*schema.Column{PostsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{},
		Indexes: []*schema.Index{
			{
				Name:    "post_title",
				Unique:  false,
				Columns: []*schema.Column{PostsColumns[1]},
			},
			{
				Name:    "post_created_at",
				Unique:  false,
				Columns: []*schema.Column{PostsColumns[2]},
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		LatestBlocksTable,
		PostsTable,
	}
)

func init() {
}
