// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"math"

	"github.com/facebook/ent/dialect/sql"
	"github.com/facebook/ent/dialect/sql/sqlgraph"
	"github.com/facebook/ent/schema/field"
	"github.com/s4kibs4mi/newschain-cache/ent/latestblock"
	"github.com/s4kibs4mi/newschain-cache/ent/predicate"
)

// LatestBlockQuery is the builder for querying LatestBlock entities.
type LatestBlockQuery struct {
	config
	limit      *int
	offset     *int
	order      []OrderFunc
	fields     []string
	predicates []predicate.LatestBlock
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the LatestBlockQuery builder.
func (lbq *LatestBlockQuery) Where(ps ...predicate.LatestBlock) *LatestBlockQuery {
	lbq.predicates = append(lbq.predicates, ps...)
	return lbq
}

// Limit adds a limit step to the query.
func (lbq *LatestBlockQuery) Limit(limit int) *LatestBlockQuery {
	lbq.limit = &limit
	return lbq
}

// Offset adds an offset step to the query.
func (lbq *LatestBlockQuery) Offset(offset int) *LatestBlockQuery {
	lbq.offset = &offset
	return lbq
}

// Order adds an order step to the query.
func (lbq *LatestBlockQuery) Order(o ...OrderFunc) *LatestBlockQuery {
	lbq.order = append(lbq.order, o...)
	return lbq
}

// First returns the first LatestBlock entity from the query.
// Returns a *NotFoundError when no LatestBlock was found.
func (lbq *LatestBlockQuery) First(ctx context.Context) (*LatestBlock, error) {
	nodes, err := lbq.Limit(1).All(ctx)
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{latestblock.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (lbq *LatestBlockQuery) FirstX(ctx context.Context) *LatestBlock {
	node, err := lbq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first LatestBlock ID from the query.
// Returns a *NotFoundError when no LatestBlock ID was found.
func (lbq *LatestBlockQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = lbq.Limit(1).IDs(ctx); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{latestblock.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (lbq *LatestBlockQuery) FirstIDX(ctx context.Context) int {
	id, err := lbq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single LatestBlock entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when exactly one LatestBlock entity is not found.
// Returns a *NotFoundError when no LatestBlock entities are found.
func (lbq *LatestBlockQuery) Only(ctx context.Context) (*LatestBlock, error) {
	nodes, err := lbq.Limit(2).All(ctx)
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{latestblock.Label}
	default:
		return nil, &NotSingularError{latestblock.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (lbq *LatestBlockQuery) OnlyX(ctx context.Context) *LatestBlock {
	node, err := lbq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only LatestBlock ID in the query.
// Returns a *NotSingularError when exactly one LatestBlock ID is not found.
// Returns a *NotFoundError when no entities are found.
func (lbq *LatestBlockQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = lbq.Limit(2).IDs(ctx); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{latestblock.Label}
	default:
		err = &NotSingularError{latestblock.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (lbq *LatestBlockQuery) OnlyIDX(ctx context.Context) int {
	id, err := lbq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of LatestBlocks.
func (lbq *LatestBlockQuery) All(ctx context.Context) ([]*LatestBlock, error) {
	if err := lbq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	return lbq.sqlAll(ctx)
}

// AllX is like All, but panics if an error occurs.
func (lbq *LatestBlockQuery) AllX(ctx context.Context) []*LatestBlock {
	nodes, err := lbq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of LatestBlock IDs.
func (lbq *LatestBlockQuery) IDs(ctx context.Context) ([]int, error) {
	var ids []int
	if err := lbq.Select(latestblock.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (lbq *LatestBlockQuery) IDsX(ctx context.Context) []int {
	ids, err := lbq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (lbq *LatestBlockQuery) Count(ctx context.Context) (int, error) {
	if err := lbq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return lbq.sqlCount(ctx)
}

// CountX is like Count, but panics if an error occurs.
func (lbq *LatestBlockQuery) CountX(ctx context.Context) int {
	count, err := lbq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (lbq *LatestBlockQuery) Exist(ctx context.Context) (bool, error) {
	if err := lbq.prepareQuery(ctx); err != nil {
		return false, err
	}
	return lbq.sqlExist(ctx)
}

// ExistX is like Exist, but panics if an error occurs.
func (lbq *LatestBlockQuery) ExistX(ctx context.Context) bool {
	exist, err := lbq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the LatestBlockQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (lbq *LatestBlockQuery) Clone() *LatestBlockQuery {
	if lbq == nil {
		return nil
	}
	return &LatestBlockQuery{
		config:     lbq.config,
		limit:      lbq.limit,
		offset:     lbq.offset,
		order:      append([]OrderFunc{}, lbq.order...),
		predicates: append([]predicate.LatestBlock{}, lbq.predicates...),
		// clone intermediate query.
		sql:  lbq.sql.Clone(),
		path: lbq.path,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		BlockNumber uint32 `json:"block_number"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.LatestBlock.Query().
//		GroupBy(latestblock.FieldBlockNumber).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
//
func (lbq *LatestBlockQuery) GroupBy(field string, fields ...string) *LatestBlockGroupBy {
	group := &LatestBlockGroupBy{config: lbq.config}
	group.fields = append([]string{field}, fields...)
	group.path = func(ctx context.Context) (prev *sql.Selector, err error) {
		if err := lbq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		return lbq.sqlQuery(), nil
	}
	return group
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		BlockNumber uint32 `json:"block_number"`
//	}
//
//	client.LatestBlock.Query().
//		Select(latestblock.FieldBlockNumber).
//		Scan(ctx, &v)
//
func (lbq *LatestBlockQuery) Select(field string, fields ...string) *LatestBlockSelect {
	lbq.fields = append([]string{field}, fields...)
	return &LatestBlockSelect{LatestBlockQuery: lbq}
}

func (lbq *LatestBlockQuery) prepareQuery(ctx context.Context) error {
	for _, f := range lbq.fields {
		if !latestblock.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if lbq.path != nil {
		prev, err := lbq.path(ctx)
		if err != nil {
			return err
		}
		lbq.sql = prev
	}
	return nil
}

func (lbq *LatestBlockQuery) sqlAll(ctx context.Context) ([]*LatestBlock, error) {
	var (
		nodes = []*LatestBlock{}
		_spec = lbq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]interface{}, error) {
		node := &LatestBlock{config: lbq.config}
		nodes = append(nodes, node)
		return node.scanValues(columns)
	}
	_spec.Assign = func(columns []string, values []interface{}) error {
		if len(nodes) == 0 {
			return fmt.Errorf("ent: Assign called without calling ScanValues")
		}
		node := nodes[len(nodes)-1]
		return node.assignValues(columns, values)
	}
	if err := sqlgraph.QueryNodes(ctx, lbq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (lbq *LatestBlockQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := lbq.querySpec()
	return sqlgraph.CountNodes(ctx, lbq.driver, _spec)
}

func (lbq *LatestBlockQuery) sqlExist(ctx context.Context) (bool, error) {
	n, err := lbq.sqlCount(ctx)
	if err != nil {
		return false, fmt.Errorf("ent: check existence: %v", err)
	}
	return n > 0, nil
}

func (lbq *LatestBlockQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := &sqlgraph.QuerySpec{
		Node: &sqlgraph.NodeSpec{
			Table:   latestblock.Table,
			Columns: latestblock.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: latestblock.FieldID,
			},
		},
		From:   lbq.sql,
		Unique: true,
	}
	if fields := lbq.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, latestblock.FieldID)
		for i := range fields {
			if fields[i] != latestblock.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := lbq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := lbq.limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := lbq.offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := lbq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector, latestblock.ValidColumn)
			}
		}
	}
	return _spec
}

func (lbq *LatestBlockQuery) sqlQuery() *sql.Selector {
	builder := sql.Dialect(lbq.driver.Dialect())
	t1 := builder.Table(latestblock.Table)
	selector := builder.Select(t1.Columns(latestblock.Columns...)...).From(t1)
	if lbq.sql != nil {
		selector = lbq.sql
		selector.Select(selector.Columns(latestblock.Columns...)...)
	}
	for _, p := range lbq.predicates {
		p(selector)
	}
	for _, p := range lbq.order {
		p(selector, latestblock.ValidColumn)
	}
	if offset := lbq.offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := lbq.limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// LatestBlockGroupBy is the group-by builder for LatestBlock entities.
type LatestBlockGroupBy struct {
	config
	fields []string
	fns    []AggregateFunc
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Aggregate adds the given aggregation functions to the group-by query.
func (lbgb *LatestBlockGroupBy) Aggregate(fns ...AggregateFunc) *LatestBlockGroupBy {
	lbgb.fns = append(lbgb.fns, fns...)
	return lbgb
}

// Scan applies the group-by query and scans the result into the given value.
func (lbgb *LatestBlockGroupBy) Scan(ctx context.Context, v interface{}) error {
	query, err := lbgb.path(ctx)
	if err != nil {
		return err
	}
	lbgb.sql = query
	return lbgb.sqlScan(ctx, v)
}

// ScanX is like Scan, but panics if an error occurs.
func (lbgb *LatestBlockGroupBy) ScanX(ctx context.Context, v interface{}) {
	if err := lbgb.Scan(ctx, v); err != nil {
		panic(err)
	}
}

// Strings returns list of strings from group-by.
// It is only allowed when executing a group-by query with one field.
func (lbgb *LatestBlockGroupBy) Strings(ctx context.Context) ([]string, error) {
	if len(lbgb.fields) > 1 {
		return nil, errors.New("ent: LatestBlockGroupBy.Strings is not achievable when grouping more than 1 field")
	}
	var v []string
	if err := lbgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// StringsX is like Strings, but panics if an error occurs.
func (lbgb *LatestBlockGroupBy) StringsX(ctx context.Context) []string {
	v, err := lbgb.Strings(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// String returns a single string from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (lbgb *LatestBlockGroupBy) String(ctx context.Context) (_ string, err error) {
	var v []string
	if v, err = lbgb.Strings(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{latestblock.Label}
	default:
		err = fmt.Errorf("ent: LatestBlockGroupBy.Strings returned %d results when one was expected", len(v))
	}
	return
}

// StringX is like String, but panics if an error occurs.
func (lbgb *LatestBlockGroupBy) StringX(ctx context.Context) string {
	v, err := lbgb.String(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Ints returns list of ints from group-by.
// It is only allowed when executing a group-by query with one field.
func (lbgb *LatestBlockGroupBy) Ints(ctx context.Context) ([]int, error) {
	if len(lbgb.fields) > 1 {
		return nil, errors.New("ent: LatestBlockGroupBy.Ints is not achievable when grouping more than 1 field")
	}
	var v []int
	if err := lbgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// IntsX is like Ints, but panics if an error occurs.
func (lbgb *LatestBlockGroupBy) IntsX(ctx context.Context) []int {
	v, err := lbgb.Ints(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Int returns a single int from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (lbgb *LatestBlockGroupBy) Int(ctx context.Context) (_ int, err error) {
	var v []int
	if v, err = lbgb.Ints(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{latestblock.Label}
	default:
		err = fmt.Errorf("ent: LatestBlockGroupBy.Ints returned %d results when one was expected", len(v))
	}
	return
}

// IntX is like Int, but panics if an error occurs.
func (lbgb *LatestBlockGroupBy) IntX(ctx context.Context) int {
	v, err := lbgb.Int(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64s returns list of float64s from group-by.
// It is only allowed when executing a group-by query with one field.
func (lbgb *LatestBlockGroupBy) Float64s(ctx context.Context) ([]float64, error) {
	if len(lbgb.fields) > 1 {
		return nil, errors.New("ent: LatestBlockGroupBy.Float64s is not achievable when grouping more than 1 field")
	}
	var v []float64
	if err := lbgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// Float64sX is like Float64s, but panics if an error occurs.
func (lbgb *LatestBlockGroupBy) Float64sX(ctx context.Context) []float64 {
	v, err := lbgb.Float64s(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64 returns a single float64 from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (lbgb *LatestBlockGroupBy) Float64(ctx context.Context) (_ float64, err error) {
	var v []float64
	if v, err = lbgb.Float64s(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{latestblock.Label}
	default:
		err = fmt.Errorf("ent: LatestBlockGroupBy.Float64s returned %d results when one was expected", len(v))
	}
	return
}

// Float64X is like Float64, but panics if an error occurs.
func (lbgb *LatestBlockGroupBy) Float64X(ctx context.Context) float64 {
	v, err := lbgb.Float64(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bools returns list of bools from group-by.
// It is only allowed when executing a group-by query with one field.
func (lbgb *LatestBlockGroupBy) Bools(ctx context.Context) ([]bool, error) {
	if len(lbgb.fields) > 1 {
		return nil, errors.New("ent: LatestBlockGroupBy.Bools is not achievable when grouping more than 1 field")
	}
	var v []bool
	if err := lbgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// BoolsX is like Bools, but panics if an error occurs.
func (lbgb *LatestBlockGroupBy) BoolsX(ctx context.Context) []bool {
	v, err := lbgb.Bools(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bool returns a single bool from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (lbgb *LatestBlockGroupBy) Bool(ctx context.Context) (_ bool, err error) {
	var v []bool
	if v, err = lbgb.Bools(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{latestblock.Label}
	default:
		err = fmt.Errorf("ent: LatestBlockGroupBy.Bools returned %d results when one was expected", len(v))
	}
	return
}

// BoolX is like Bool, but panics if an error occurs.
func (lbgb *LatestBlockGroupBy) BoolX(ctx context.Context) bool {
	v, err := lbgb.Bool(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (lbgb *LatestBlockGroupBy) sqlScan(ctx context.Context, v interface{}) error {
	for _, f := range lbgb.fields {
		if !latestblock.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("invalid field %q for group-by", f)}
		}
	}
	selector := lbgb.sqlQuery()
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := lbgb.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

func (lbgb *LatestBlockGroupBy) sqlQuery() *sql.Selector {
	selector := lbgb.sql
	columns := make([]string, 0, len(lbgb.fields)+len(lbgb.fns))
	columns = append(columns, lbgb.fields...)
	for _, fn := range lbgb.fns {
		columns = append(columns, fn(selector, latestblock.ValidColumn))
	}
	return selector.Select(columns...).GroupBy(lbgb.fields...)
}

// LatestBlockSelect is the builder for selecting fields of LatestBlock entities.
type LatestBlockSelect struct {
	*LatestBlockQuery
	// intermediate query (i.e. traversal path).
	sql *sql.Selector
}

// Scan applies the selector query and scans the result into the given value.
func (lbs *LatestBlockSelect) Scan(ctx context.Context, v interface{}) error {
	if err := lbs.prepareQuery(ctx); err != nil {
		return err
	}
	lbs.sql = lbs.LatestBlockQuery.sqlQuery()
	return lbs.sqlScan(ctx, v)
}

// ScanX is like Scan, but panics if an error occurs.
func (lbs *LatestBlockSelect) ScanX(ctx context.Context, v interface{}) {
	if err := lbs.Scan(ctx, v); err != nil {
		panic(err)
	}
}

// Strings returns list of strings from a selector. It is only allowed when selecting one field.
func (lbs *LatestBlockSelect) Strings(ctx context.Context) ([]string, error) {
	if len(lbs.fields) > 1 {
		return nil, errors.New("ent: LatestBlockSelect.Strings is not achievable when selecting more than 1 field")
	}
	var v []string
	if err := lbs.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// StringsX is like Strings, but panics if an error occurs.
func (lbs *LatestBlockSelect) StringsX(ctx context.Context) []string {
	v, err := lbs.Strings(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// String returns a single string from a selector. It is only allowed when selecting one field.
func (lbs *LatestBlockSelect) String(ctx context.Context) (_ string, err error) {
	var v []string
	if v, err = lbs.Strings(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{latestblock.Label}
	default:
		err = fmt.Errorf("ent: LatestBlockSelect.Strings returned %d results when one was expected", len(v))
	}
	return
}

// StringX is like String, but panics if an error occurs.
func (lbs *LatestBlockSelect) StringX(ctx context.Context) string {
	v, err := lbs.String(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Ints returns list of ints from a selector. It is only allowed when selecting one field.
func (lbs *LatestBlockSelect) Ints(ctx context.Context) ([]int, error) {
	if len(lbs.fields) > 1 {
		return nil, errors.New("ent: LatestBlockSelect.Ints is not achievable when selecting more than 1 field")
	}
	var v []int
	if err := lbs.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// IntsX is like Ints, but panics if an error occurs.
func (lbs *LatestBlockSelect) IntsX(ctx context.Context) []int {
	v, err := lbs.Ints(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Int returns a single int from a selector. It is only allowed when selecting one field.
func (lbs *LatestBlockSelect) Int(ctx context.Context) (_ int, err error) {
	var v []int
	if v, err = lbs.Ints(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{latestblock.Label}
	default:
		err = fmt.Errorf("ent: LatestBlockSelect.Ints returned %d results when one was expected", len(v))
	}
	return
}

// IntX is like Int, but panics if an error occurs.
func (lbs *LatestBlockSelect) IntX(ctx context.Context) int {
	v, err := lbs.Int(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64s returns list of float64s from a selector. It is only allowed when selecting one field.
func (lbs *LatestBlockSelect) Float64s(ctx context.Context) ([]float64, error) {
	if len(lbs.fields) > 1 {
		return nil, errors.New("ent: LatestBlockSelect.Float64s is not achievable when selecting more than 1 field")
	}
	var v []float64
	if err := lbs.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// Float64sX is like Float64s, but panics if an error occurs.
func (lbs *LatestBlockSelect) Float64sX(ctx context.Context) []float64 {
	v, err := lbs.Float64s(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64 returns a single float64 from a selector. It is only allowed when selecting one field.
func (lbs *LatestBlockSelect) Float64(ctx context.Context) (_ float64, err error) {
	var v []float64
	if v, err = lbs.Float64s(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{latestblock.Label}
	default:
		err = fmt.Errorf("ent: LatestBlockSelect.Float64s returned %d results when one was expected", len(v))
	}
	return
}

// Float64X is like Float64, but panics if an error occurs.
func (lbs *LatestBlockSelect) Float64X(ctx context.Context) float64 {
	v, err := lbs.Float64(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bools returns list of bools from a selector. It is only allowed when selecting one field.
func (lbs *LatestBlockSelect) Bools(ctx context.Context) ([]bool, error) {
	if len(lbs.fields) > 1 {
		return nil, errors.New("ent: LatestBlockSelect.Bools is not achievable when selecting more than 1 field")
	}
	var v []bool
	if err := lbs.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// BoolsX is like Bools, but panics if an error occurs.
func (lbs *LatestBlockSelect) BoolsX(ctx context.Context) []bool {
	v, err := lbs.Bools(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bool returns a single bool from a selector. It is only allowed when selecting one field.
func (lbs *LatestBlockSelect) Bool(ctx context.Context) (_ bool, err error) {
	var v []bool
	if v, err = lbs.Bools(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{latestblock.Label}
	default:
		err = fmt.Errorf("ent: LatestBlockSelect.Bools returned %d results when one was expected", len(v))
	}
	return
}

// BoolX is like Bool, but panics if an error occurs.
func (lbs *LatestBlockSelect) BoolX(ctx context.Context) bool {
	v, err := lbs.Bool(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (lbs *LatestBlockSelect) sqlScan(ctx context.Context, v interface{}) error {
	rows := &sql.Rows{}
	query, args := lbs.sqlQuery().Query()
	if err := lbs.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

func (lbs *LatestBlockSelect) sqlQuery() sql.Querier {
	selector := lbs.sql
	selector.Select(selector.Columns(lbs.fields...)...)
	return selector
}
