// Code generated by entc, DO NOT EDIT.

package predicate

import (
	"github.com/facebook/ent/dialect/sql"
)

// LatestBlock is the predicate function for latestblock builders.
type LatestBlock func(*sql.Selector)

// Post is the predicate function for post builders.
type Post func(*sql.Selector)
